### ISSUE TITLE
Fill in navbar content

### ISSUE THREAD

**Issue by Kataract** [pyohio/pyohio-static-website#12]
Need links to content and what goes where, assuming we're not mirroring the 2018 site.

Note that this is technically doable but is going to take some effort to override Bulma's strong selector coupling and to make the menus keyboard accessible.

**Comment by tylerdave** [comment]
I've added a working draft of the menu structure in my `import-static-pages` branch here:
https://github.com/pyohio/pyohio-static-website/blob/import-static-pages/src/pages/nav.md

I'm filling in the pages w/ the content from last year and once that's done I'll merge it w/ the pages existing but unlinked.

**Comment by Kataract** [comment]
Started work in branch `navbar-content`.

To dos:
* Add `is-active` class on the parent dropdown `<div>` when the associated child button is clicked
* Figure out why only the About button renders incorrectly in React so that it's not actually clickable
* Make an attempt to reconcile the `aria-expanded` attributes with the hamburger view, since they're permanently open and can possibly misreport
