### ISSUE TITLE
list of dates

### ISSUE THREAD

**Issue by reshamas** [pyohio/pyohio-static-website#131]
Current
```text
CFP: Open mid-March though mid-April. Details TBA!
Registrion: Opens in May
Talks: Announced in June
Schedule: Announced in July
T-shirt sales: Coming soon!
```

Suggestions:
- update spelling to "Registration"
- perhaps add another line after "Schedule" that reads "Day of Online Conference: July 30, 2022"

**Comment by tylerdave** [comment]
Fixed the typo in #132. The rest is placeholder text while we figure out details over the next ~week so it'll be updated along w/ other homepage changes then. Thanks again @reshamas!
