### ISSUE TITLE
Add Premier sponsor acknowledgement footer

### ISSUE THREAD

**Issue by tylerdave** [pyohio/pyohio-static-website#17]
One of the sponsor benefits for the Premier tier is a link and logo in the footer of the site. Add that capability now so it's ready to go when the sponsor is activated. 

If it's easy enough to get the data via query, cool. If not feel free to directly include the necessary HTML in the layout component directly.

**Comment by Kataract** [comment]
Started here: https://github.com/pyohio/pyohio-static-website/tree/sponsor-display

Needs a query to fill in the `<img>` and then the footer can be uncommented.

**Comment by tylerdave** [comment]
I'm thinking a `StaticQuery` might make the most sense here?

https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/static-query.md

Query to get premier sponsor name and resized logo:

```  allSponsorLevels(filter: {name: {eq: "Premier"}}) {
    edges {
      node {
        name
        sponsors {
          name
          web_logo {
            local{
              childImageSharp{
                resize(height: 50) {
                  src
                  tracedSVG
                  width
                  height
                  aspectRatio
                  originalName
                }
              }
            }
          }
        }
      }
    }
  } ```

For testing you can replace `Premier` with `Non-Profit` since there's one of those. The actual sponsor should be activated soon. 

If all this is too much we can totally just explicitly name the sponsor and link the image. It's not like it's going to change for a year+.
