### ISSUE TITLE
Add 2019 logo to homepage

### ISSUE THREAD

**Issue by tylerdave** [pyohio/pyohio-static-website#19]
Once we have a final logo for 2019, include it prominently on the homepage.

**Comment by tylerdave** [comment]
Logos have been added here: https://github.com/pyohio/pyohio-static-website/tree/master/static/img

**Comment by tylerdave** [comment]
Slapped the image on the homepage... Feel free to improve the layout to make the homepage look better. 

(I'm still having an issue w/ the image path mis-matching in dev vs prod due to the `pathPrefix` setting. Likely related to #15.)

**Comment by Kataract** [comment]
Believe we've done enough to justify closing this.
