### ISSUE TITLE
Page content overflows bottom border

### ISSUE THREAD

**Issue by tylerdave** [pyohio/pyohio-static-website#77]
The content of multiple pages overflows the bottom border.

**Example from Events page:**
<img width="1166" alt="Screen Shot 2020-07-05 at 9 28 30 PM" src="https://user-images.githubusercontent.com/409205/86547477-2e426180-bf07-11ea-8556-8b1ee349eb0e.png">

**Comment by hunj** [comment]
I noticed it was due to the wrapper <div> being a grid. I tried changing that to block in my browser and it looked fixed.
