### ISSUE TITLE
Newsletter sign up is broken

### ISSUE THREAD

**Issue by jugmac00** [pyohio/pyohio-static-website#84]
first reported on Twitter
https://twitter.com/jugmac00/status/1281167236091252736

**Comment by tylerdave** [comment]
Thanks for opening the issue @jugmac00! Will check it out.

The form has been problematic. Can probably address along with #38

**Comment by tylerdave** [comment]
Looks to be something to do w/ React state but I couldn't figure out a quick fix.

This might be helpful but I haven't had time to experiment yet: https://www.npmjs.com/package/react-mailchimp-subscribe

Temporarily switching to a direct link to the hosted signup form.

**Comment by jugmac00** [comment]
Looks like you use MailChimp now? Closing this ticket.
